# Generated by Django 4.2.7 on 2023-11-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='record',
            name='address',
            field=models.CharField(max_length=50),
        ),
    ]
